import { useEffect, useState } from "react";
import { ArrowRight, ArrowUpRight, BellRing, Database, FilePlus2, Search, ShieldCheck } from "lucide-react";
import { Link } from "wouter";
import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { SiteFooter, SiteHeader } from "@/components/SiteChrome";
import { trpc } from "@/lib/trpc";

type AdminTab = "overview" | "territories" | "users" | "orders" | "payments" | "ledger" | "reports" | "announcements" | "audit";
type ReportRow = { label: string; total: number };
const money = (value: string | number) => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 2 }).format(Number(value));

function ReportGroup({ title, rows }: { title: string; rows: ReportRow[] }) {
  return <section className="admin-report-group"><h3>{title}</h3>{rows.length ? rows.map(row => <div className="admin-report-row" key={row.label}><span>{row.label.replaceAll("_", " ")}</span><strong>{row.total.toLocaleString("en-IN")}</strong></div>) : <p>No records.</p>}</section>;
}

export function AdminPage({ initialTab = "overview" }: { initialTab?: AdminTab }) {
  const { user, loading } = useAuth();
  const admin = user?.role === "admin";
  const [tab, setTab] = useState<AdminTab>(initialTab);
  const [notice, setNotice] = useState("");
  const [priceDrafts, setPriceDrafts] = useState<Record<string, string>>({});
  const [announcement, setAnnouncement] = useState({ title: "", body: "" });
  const [formOpen, setFormOpen] = useState(false);
  const [form, setForm] = useState({ territoryId: "", name: "", region: "", country: "", latitude: "", longitude: "", areaUnits: "", rarity: "COMMON", price: "", status: "AVAILABLE", historicalNote: "" });
  const utils = trpc.useUtils();
  const overview = trpc.admin.overview.useQuery(undefined, { enabled: admin && tab === "overview" });
  const territories = trpc.admin.territories.useQuery(undefined, { enabled: admin && tab === "territories" });
  const users = trpc.admin.users.useQuery(undefined, { enabled: admin && tab === "users" });
  const orders = trpc.admin.orders.useQuery(undefined, { enabled: admin && tab === "orders" });
  const payments = trpc.admin.payments.useQuery(undefined, { enabled: admin && tab === "payments" });
  const ledger = trpc.admin.ledger.useQuery(undefined, { enabled: admin && tab === "ledger" });
  const reports = trpc.admin.reports.useQuery(undefined, { enabled: admin && tab === "reports" });
  const audit = trpc.admin.audit.useQuery(undefined, { enabled: admin && tab === "audit" });
  const create = trpc.territories.adminCreate.useMutation({ onSuccess: async () => { await utils.admin.territories.invalidate(); await utils.territories.list.invalidate(); setFormOpen(false); setNotice("Catalog record created."); } });
  const status = trpc.territories.adminSetStatus.useMutation({ onSuccess: async () => { await utils.admin.territories.invalidate(); await utils.territories.list.invalidate(); setNotice("Territory status updated."); } });
  const updatePrice = trpc.admin.updatePrice.useMutation({ onSuccess: async (_, variables) => { await utils.admin.territories.invalidate(); await utils.territories.list.invalidate(); setNotice(`Price updated for ${variables.territoryId}.`); } });
  const sendAnnouncement = trpc.admin.announce.useMutation({ onSuccess: async result => { await utils.admin.audit.invalidate(); setNotice(`Announcement sent to ${result.recipients} account(s).`); setAnnouncement({ title: "", body: "" }); } });
  const setField = (key: keyof typeof form, value: string) => setForm(current => ({ ...current, [key]: value }));
  useEffect(() => setTab(initialTab), [initialTab]);

  if (loading) return <div className="site-page"><SiteHeader /><main className="inner-page"><div className="catalog-empty">Checking administrator session…</div></main></div>;
  if (!user) return <div className="site-page"><SiteHeader /><main className="inner-page"><div className="catalog-empty auth-message"><span className="eyebrow">ADMIN ACCESS</span><strong>Sign in to continue.</strong><button className="button-primary" onClick={() => startLogin()}>Sign in <ArrowRight size={16} /></button></div></main><SiteFooter /></div>;
  if (!admin) return <div className="site-page"><SiteHeader /><main className="inner-page"><div className="catalog-empty auth-message"><ShieldCheck size={22} /><strong>Administrator access required.</strong><p>This area is protected by server-side role authorization.</p><Link href="/dashboard" className="text-link">Return to dashboard <ArrowRight size={15} /></Link></div></main><SiteFooter /></div>;

  const tabs: [AdminTab, string][] = [["overview", "Overview"], ["territories", "Territories"], ["users", "Users"], ["orders", "Orders"], ["payments", "Payments"], ["ledger", "Ledger"], ["reports", "Reports"], ["announcements", "Announcements"], ["audit", "Audit log"]];
  return <div className="site-page"><SiteHeader /><main className="inner-page admin-page">
    <div className="page-intro"><div className="eyebrow"><span className="signal-dot" /> SYSTEM CONTROL / ADMIN</div><h1>Platform<br /><span>command.</span></h1><p>Operational records and catalog controls. Every administrative write is authorized server-side and recorded in the audit log.</p></div>
    <div className="admin-tabs" role="tablist" aria-label="Administrator sections">{tabs.map(([key, label]) => <button key={key} role="tab" aria-selected={tab === key} className={tab === key ? "active" : ""} onClick={() => { setNotice(""); setTab(key); }}>{label}</button>)}</div>
    {notice && <p className="admin-notice" role="status">{notice}</p>}
    {tab === "overview" && <section className="admin-content">{overview.isLoading ? <div className="quiet-state">Loading platform records…</div> : overview.error ? <div className="catalog-empty catalog-empty--error">Admin data unavailable: {overview.error.message}</div> : overview.data && <><div className="eyebrow">DATABASE COUNTS / LIVE</div><div className="stat-grid"><article><span>USER RECORDS</span><strong>{overview.data.users.toLocaleString()}</strong></article><article><span>TERRITORIES</span><strong>{overview.data.territories.toLocaleString()}</strong></article><article><span>ORDERS</span><strong>{overview.data.orders.toLocaleString()}</strong></article><article><span>PAYMENTS</span><strong>{overview.data.payments.toLocaleString()}</strong></article><article><span>LEDGER ENTRIES</span><strong>{overview.data.ledgerEntries.toLocaleString()}</strong></article></div><div className="legal-callout"><Database size={16} /> Counts are read from the active managed application database. No demo records are seeded.</div></>}</section>}
    {tab === "territories" && <section className="admin-content"><div className="account-section-head"><div><span className="eyebrow">CATALOG CONTROL</span><h2>Territory records</h2></div><button className="button-primary" onClick={() => setFormOpen(value => !value)}><FilePlus2 size={16} /> {formOpen ? "Close form" : "Add territory"}</button></div>
      {formOpen && <form className="territory-form" onSubmit={event => { event.preventDefault(); create.mutate({ territoryId: form.territoryId, name: form.name, region: form.region, country: form.country, latitude: Number(form.latitude), longitude: Number(form.longitude), areaUnits: Number(form.areaUnits), rarity: form.rarity as "COMMON" | "RARE" | "EPIC" | "LEGENDARY" | "MYTHIC", price: Number(form.price), status: form.status as "AVAILABLE" | "FEATURED" | "LOCKED", historicalNote: form.historicalNote || undefined }); }}>
        <div className="form-grid"><label>Territory ID<input required pattern="E616-[0-9]{6}" placeholder="E616-000421" value={form.territoryId} onChange={event => setField("territoryId", event.target.value)} /></label><label>Name<input required minLength={2} maxLength={120} value={form.name} onChange={event => setField("name", event.target.value)} /></label><label>Region<input required maxLength={80} value={form.region} onChange={event => setField("region", event.target.value)} /></label><label>Country<input required maxLength={80} value={form.country} onChange={event => setField("country", event.target.value)} /></label><label>Latitude<input required type="number" min="-90" max="90" step="0.000001" value={form.latitude} onChange={event => setField("latitude", event.target.value)} /></label><label>Longitude<input required type="number" min="-180" max="180" step="0.000001" value={form.longitude} onChange={event => setField("longitude", event.target.value)} /></label><label>Area / units<input required type="number" min="0.01" step="0.01" value={form.areaUnits} onChange={event => setField("areaUnits", event.target.value)} /></label><label>Rarity<select value={form.rarity} onChange={event => setField("rarity", event.target.value)}>{["COMMON", "RARE", "EPIC", "LEGENDARY", "MYTHIC"].map(value => <option key={value}>{value}</option>)}</select></label><label>Platform price (₹)<input required type="number" min="0.01" step="0.01" value={form.price} onChange={event => setField("price", event.target.value)} /></label><label>Status<select value={form.status} onChange={event => setField("status", event.target.value)}>{["AVAILABLE", "FEATURED", "LOCKED"].map(value => <option key={value}>{value}</option>)}</select></label><label className="form-span">Catalog note<textarea maxLength={2000} rows={3} value={form.historicalNote} onChange={event => setField("historicalNote", event.target.value)} /></label></div>
        {create.error && <p className="form-error" role="alert">{create.error.message}</p>}<button className="button-primary" disabled={create.isPending}>{create.isPending ? "Saving record…" : "Create catalog record"}<ArrowRight size={16} /></button><p className="dialog-note">Adding a territory creates a digital catalog record only; it does not represent physical land ownership.</p>
      </form>}
      {territories.isLoading ? <div className="quiet-state">Loading territory records…</div> : territories.error ? <div className="catalog-empty catalog-empty--error">{territories.error.message}</div> : territories.data?.length ? <div className="admin-table">{territories.data.map(item => <div className="admin-row admin-territory-row" key={item.territoryId}><span>{item.territoryId}<small>{item.rarity}</small></span><strong>{item.name}<small>{item.region}</small></strong><label className="admin-price-field"><span className="sr-only">Current price for {item.territoryId}</span><input type="number" min="0.01" step="0.01" value={priceDrafts[item.territoryId] ?? Number(item.currentPrice).toFixed(2)} onChange={event => setPriceDrafts(current => ({ ...current, [item.territoryId]: event.target.value }))} /><small>PRICE · INR</small></label><button className="admin-small-action" disabled={updatePrice.isPending || item.status === "OWNED"} onClick={() => updatePrice.mutate({ territoryId: item.territoryId, price: Number(priceDrafts[item.territoryId] ?? item.currentPrice) })}>Update price</button><label className="status-control"><span className="sr-only">Set status for {item.territoryId}</span><select value={item.status} disabled={item.status === "OWNED" || status.isPending} onChange={event => status.mutate({ territoryId: item.territoryId, status: event.target.value as "AVAILABLE" | "FEATURED" | "LOCKED" })}><option>AVAILABLE</option><option>FEATURED</option><option>LOCKED</option><option disabled>OWNED</option></select></label></div>)}</div> : <div className="account-empty"><strong>The catalog is empty.</strong><p>Add the first digital territory record when its metadata and price have been reviewed.</p></div>}
      {(create.error || status.error || updatePrice.error) && <p className="form-error" role="alert">{create.error?.message || status.error?.message || updatePrice.error?.message}</p>}
    </section>}
    {tab === "users" && <section className="admin-content"><div className="account-section-head"><h2>User records</h2><span>SERVER-SCOPED · MAX 100</span></div>{users.isLoading ? <div className="quiet-state">Loading users…</div> : users.error ? <div className="catalog-empty catalog-empty--error">{users.error.message}</div> : users.data?.length ? <div className="admin-table">{users.data.map(item => <div className="admin-row" key={item.id}><span>USER / {item.id}</span><strong>{item.name || "No display name"}<small>{item.email || "No email on record"}</small></strong><span>{item.role.toUpperCase()}<small>{new Date(item.joinedAt).toLocaleDateString()}</small></span></div>)}</div> : <div className="account-empty">No user records.</div>}</section>}
    {tab === "orders" && <section className="admin-content"><div className="account-section-head"><h2>Orders</h2><span>NO CLIENT-ASSERTED PAYMENT SUCCESS</span></div>{orders.isLoading ? <div className="quiet-state">Loading orders…</div> : orders.error ? <div className="catalog-empty catalog-empty--error">{orders.error.message}</div> : orders.data?.length ? <div className="admin-table">{orders.data.map(item => <div className="admin-row" key={item.id}><span>{item.id.slice(0, 8)}…<small>{new Date(item.createdAt).toLocaleString()}</small></span><strong>{item.territoryId}<small>USER / {item.userId}</small></strong><span>{money(item.amount)}<small>{item.currency} · {item.status}</small></span></div>)}</div> : <div className="account-empty"><strong>No orders recorded.</strong><p>Orders will appear only after a verified checkout flow is enabled.</p></div>}</section>}
    {tab === "payments" && <section className="admin-content"><div className="account-section-head"><h2>Payments</h2><span>PROVIDER METADATA ONLY · MAX 100</span></div>{payments.isLoading ? <div className="quiet-state">Loading payment records…</div> : payments.error ? <div className="catalog-empty catalog-empty--error">{payments.error.message}</div> : payments.data?.length ? <div className="admin-table">{payments.data.map(item => <div className="admin-row admin-finance-row" key={item.id}><span>{item.provider}<small>{item.providerOrderId || "No provider order"}</small></span><strong>{item.providerPaymentId || "Awaiting provider payment"}<small>ORDER / {item.orderId.slice(0, 8)}…</small></strong><span>{money(item.amount)}<small>{item.status}</small></span><span>{item.signatureVerified ? "VERIFIED" : "UNVERIFIED"}<small>{new Date(item.updatedAt).toLocaleString()}</small></span></div>)}</div> : <div className="account-empty"><strong>No payment records.</strong><p>Payment processing is intentionally disabled until server-side verification is configured.</p></div>}</section>}
    {tab === "ledger" && <section className="admin-content"><div className="account-section-head"><h2>Wallet ledger</h2><span>APPEND-ONLY RECORDS · MAX 100</span></div>{ledger.isLoading ? <div className="quiet-state">Loading ledger records…</div> : ledger.error ? <div className="catalog-empty catalog-empty--error">{ledger.error.message}</div> : ledger.data?.length ? <div className="admin-table">{ledger.data.map(item => <div className="admin-row admin-finance-row" key={item.id}><span>USER / {item.userId}<small>{item.type}</small></span><strong>{money(item.amount)}<small>Balance after · {money(item.balanceAfter)}</small></strong><span>{item.status}<small>{item.referenceId || "No reference"}</small></span><span>{new Date(item.createdAt).toLocaleString()}<small>{item.memo || ""}</small></span></div>)}</div> : <div className="account-empty"><strong>No ledger entries.</strong><p>Credits and debits are not client-editable; a verified settlement flow is required.</p></div>}</section>}
    {tab === "reports" && <section className="admin-content"><div className="account-section-head"><h2>Platform reports</h2><span>LIVE DATABASE AGGREGATES</span></div>{reports.isLoading ? <div className="quiet-state">Loading report data…</div> : reports.error ? <div className="catalog-empty catalog-empty--error">{reports.error.message}</div> : reports.data && <div className="admin-report-grid"><ReportGroup title="Users by role" rows={reports.data.usersByRole} /><ReportGroup title="Territories by status" rows={reports.data.territoriesByStatus} /><ReportGroup title="Orders by status" rows={reports.data.ordersByStatus} /><ReportGroup title="Payments by status" rows={reports.data.paymentsByStatus} /></div>}</section>}
    {tab === "announcements" && <section className="admin-content"><div className="account-section-head"><div><span className="eyebrow">USER COMMUNICATION</span><h2>Platform announcement</h2></div><BellRing size={20} /></div><p className="admin-subcopy">Create a notification for every registered account. The recipient count and announcement metadata are audit logged; a broadcast is limited to 1,000 accounts per operation.</p><form className="announcement-form" onSubmit={event => { event.preventDefault(); sendAnnouncement.mutate(announcement); }}><label>Announcement title<input required minLength={3} maxLength={120} value={announcement.title} onChange={event => setAnnouncement(current => ({ ...current, title: event.target.value }))} /></label><label>Message<textarea required minLength={3} maxLength={500} rows={4} value={announcement.body} onChange={event => setAnnouncement(current => ({ ...current, body: event.target.value }))} /></label>{sendAnnouncement.error && <p className="form-error" role="alert">{sendAnnouncement.error.message}</p>}<button className="button-primary" disabled={sendAnnouncement.isPending}>{sendAnnouncement.isPending ? "Sending…" : "Send to users"}<ArrowRight size={16} /></button></form></section>}
    {tab === "audit" && <section className="admin-content"><div className="account-section-head"><h2>Admin audit log</h2><span>WRITE HISTORY · MAX 100</span></div>{audit.isLoading ? <div className="quiet-state">Loading audit records…</div> : audit.error ? <div className="catalog-empty catalog-empty--error">{audit.error.message}</div> : audit.data?.length ? <div className="admin-table">{audit.data.map(item => <div className="admin-row admin-finance-row" key={item.id}><span>{new Date(item.createdAt).toLocaleString()}<small>ADMIN / {item.adminUserId}</small></span><strong>{item.action}<small>{item.entityType} / {item.entityId}</small></strong><span>{item.details || "No additional detail"}</span></div>)}</div> : <div className="account-empty"><strong>No administrative actions recorded yet.</strong><p>Catalog writes and announcements are audit-logged when they occur.</p></div>}</section>}
    <div className="admin-shortcuts"><span className="eyebrow">ADMIN AREAS</span><Link href="/admin/transactions">Transactions <ArrowUpRight size={14} /></Link><Link href="/admin/topups">Wallet top-ups <ArrowUpRight size={14} /></Link><Link href="/admin/orders">Orders <ArrowUpRight size={14} /></Link><Link href="/admin/reports">Reports <ArrowUpRight size={14} /></Link><Link href="/admin/settings">Settings & announcements <ArrowUpRight size={14} /></Link></div>
  </main><SiteFooter /></div>;
}
