import { ArrowLeft, ArrowRight, ArrowUpRight, Check, Fingerprint, Globe2, ShieldCheck } from "lucide-react";
import { Link } from "wouter";
import { useState } from "react";
import { SiteFooter, SiteHeader } from "@/components/SiteChrome";
import { trpc } from "@/lib/trpc";

const pages: Record<string, { number: string; eyebrow: string; title: [string, string]; lead: string; sections: [string, string][] }> = {
  about: { number: "09", eyebrow: "ABOUT EARTH616", title: ["A world to", "make your own."], lead: "EARTH616 is a digital territory platform built around exploration, identity, and community presence.", sections: [["Digital by design", "EARTH616 territories are digital platform records. They are not parcels of physical land, real estate, or sovereign territory."], ["Built on clear rules", "Catalog data and activity are governed by the platform. Prices, ownership, and Territory Power are maintained on the server; browser state cannot assign them."], ["An evolving atlas", "The territory catalog, rankings, and community features grow from actual platform records. Empty views remain empty until real records exist."]] },
  "how-it-works": { number: "10", eyebrow: "THE SYSTEM", title: ["Explore.", "Claim. Build."], lead: "A straightforward path through the digital atlas, with every important action backed by the platform record.", sections: [["01 — Explore", "Browse territories from the live catalog, inspect availability, region, rarity, coordinates, and current platform price."], ["02 — Claim digitally", "Where payment is enabled, a territory claim must follow server-side price lookup and verified payment before an ownership record can be created. The browser cannot declare a payment successful."], ["03 — Shape your identity", "Your EARTH616 profile brings your username, identity level, achievements, and activity together. These levels describe participation, not financial status."], ["04 — Grow Territory Power", "Power is calculated by server-owned logic from territory attributes and qualifying activity. A client cannot directly assign itself a score."]] },
  legal: { number: "11", eyebrow: "PLATFORM BOUNDARIES", title: ["Know what", "EARTH616 is."], lead: "EARTH616 is a digital platform. The following distinction is fundamental to how territories are represented.", sections: [["Digital territories only", "A territory is a digital record within EARTH616. A platform claim does not create, evidence, or transfer legal ownership of physical land, real estate, geographic property, or sovereign territory."], ["Internal platform credits", "E616 is an internal platform credit/ledger unit for the MVP. It is not cryptocurrency, a security, an investment product, guaranteed-return asset, or legal tender."], ["No return promise", "Catalog price and Territory Power are platform attributes. Neither is presented as a promise of profit, appreciation, or future value."], ["Payments", "No purchase should be considered complete based on a browser message. Any production purchase flow must be authenticated, idempotent, and finalized only after server-side payment verification."]] },
  privacy: { number: "12", eyebrow: "PRIVACY", title: ["Your identity", "stays yours."], lead: "This page summarizes the current EARTH616 app's data model. Publish a jurisdiction-specific privacy policy after legal review before opening the platform to the public.", sections: [["Account data", "Authentication is handled through the project session provider. EARTH616 stores the profile attributes needed to provide identity and platform features."], ["Platform activity", "Territory interactions, wallet ledger entries, notifications, and administrative actions are stored only as needed for platform operation and auditability."], ["No payment secrets in the browser", "Payment credentials and verification secrets belong only in protected server configuration. Sensitive payment data must not be written to logs."], ["Contact and retention", "Production contact details, data-export procedures, retention periods, and jurisdiction-specific rights have not yet been configured. Do not treat this development deployment as a published privacy policy."]] },
  terms: { number: "13", eyebrow: "TERMS", title: ["A digital", "platform only."], lead: "This development experience is not a substitute for final product terms reviewed for your operating jurisdictions.", sections: [["Nature of the service", "EARTH616 provides access to digital platform territories, identity features, and related experiences. It does not convey physical property rights."], ["E616", "E616 is an internal platform credit unit for the MVP, not cryptocurrency, legal tender, a security, or an investment."], ["Availability", "Territory availability and pricing are read from platform records and may change under authorized platform controls. A listing is not a guaranteed offer until a verified order flow is active."], ["Production launch", "Before public launch, replace this summary with finalized terms, refund rules, service limits, and jurisdiction-specific disclosures reviewed by qualified counsel."]] },
};

export function InfoPage({ kind }: { kind: keyof typeof pages }) {
  const page = pages[kind];
  return <div className="site-page"><SiteHeader /><main className="inner-page info-page">
    <Link href="/" className="back-link"><ArrowLeft size={16} /> EARTH616</Link>
    <div className="page-intro"><div className="eyebrow"><span className="signal-dot" /> {page.eyebrow} / {page.number}</div><h1>{page.title[0]}<br /><span>{page.title[1]}</span></h1><p>{page.lead}</p></div>
    <div className="info-layout"><aside className="info-index"><span>ON THIS PAGE</span>{page.sections.map(([title], index) => <a href={`#info-${index}`} key={title}>{String(index + 1).padStart(2, "0")} / {title}</a>)}</aside><div className="info-sections">{page.sections.map(([title, body], index) => <article id={`info-${index}`} key={title}><div className="eyebrow">SECTION {String(index + 1).padStart(2, "0")}</div><h2>{title}</h2><p>{body}</p></article>)}</div></div>
    <div className="info-end"><span>EARTH616 / DIGITAL TERRITORIES ONLY</span><Link href="/explore" className="text-link">Explore Earth <ArrowRight size={15} /></Link></div>
  </main><SiteFooter /></div>;
}

export function RankingsPage() {
  const [category, setCategory] = useState<"power" | "territories">("power");
  const rankings = trpc.territories.rankings.useQuery({ category, limit: 50 });
  return <div className="site-page"><SiteHeader /><main className="inner-page rankings-page">
    <div className="page-intro"><div className="eyebrow"><span className="signal-dot" /> GLOBAL RANKINGS / LIVE DATA</div><h1>Make your<br /><span>mark.</span></h1><p>Rankings are computed from recorded platform profiles. No sample users or placeholder scores are shown.</p></div>
    <div className="ranking-tabs" role="tablist" aria-label="Ranking category">
      <button role="tab" aria-selected={category === "power"} className={category === "power" ? "active" : ""} onClick={() => setCategory("power")}>Highest Territory Power</button>
      <button role="tab" aria-selected={category === "territories"} className={category === "territories" ? "active" : ""} onClick={() => setCategory("territories")}>Most Territories</button>
      <span className="coming-soon-tab">Rarest Territories <small>COMING SOON</small></span><span className="coming-soon-tab">Top Builders <small>COMING SOON</small></span><span className="coming-soon-tab">Rising Players <small>COMING SOON</small></span>
    </div>
    <div className="rank-table-head"><span>RANK / IDENTITY</span><span>{category === "power" ? "TERRITORY POWER" : "TERRITORIES"}</span></div>
    {rankings.isLoading ? <div className="catalog-empty">Loading platform rankings…</div> : rankings.error ? <div className="catalog-empty catalog-empty--error">Rankings are temporarily unavailable.</div> : rankings.data?.entries.length ? <div className="leader-list">{rankings.data.entries.map((entry, index) => <div className="leader-row ranking-row" key={entry.identityId}><span className="leader-rank">{String(index + 1).padStart(2, "0")}</span><span className="leader-name">{entry.displayName}<small>@{entry.username} · {entry.identityId}</small></span><span className="leader-power">{(category === "power" ? entry.territoryPower : entry.territoryCount).toLocaleString()} <small>{category === "power" ? "POWER" : "TERRITORIES"}</small></span></div>)}</div> : <div className="catalog-empty"><div className="empty-orbit" /><strong>No ranked profiles yet.</strong><p>Once genuine platform activity is recorded, it will appear here.</p><Link href="/explore" className="text-link">Explore Earth <ArrowRight size={15} /></Link></div>}
    <p className="legal-callout">Territory Power is a platform participation score only. It is not a financial metric or investment signal.</p>
  </main><SiteFooter /></div>;
}
